
import { Anek_Bangla } from "next/font/google";
import "../../globals.css";

import AdminSidebar from "@/components/admin/AdminSidebar";
import AdminHeader from "@/components/admin/AdminHeader";

const anekBangla = Anek_Bangla({
  subsets: ["bengali", "latin"],
  variable: "--font-anek-bangla",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AdmintLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={`${anekBangla.variable} h-full antialiased`}
    >
      <body className="">
        <div className="min-h-screen bg-gray-100">
          <AdminSidebar />
          <div className="lg:pl-72">
            <AdminHeader />

            <main className="p-4 md:p-6 lg:p-8">{children}</main>
          </div>
        </div>
      </body>
    </html>
  );
}
