// import { Geist, Geist_Mono, } from "next/font/google";

import { Anek_Bangla } from "next/font/google";
import "../globals.css";

import Navbar from "@/components/header/Navbar";
import Footer from "@/components/footer/Footer";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const anekBangla = Anek_Bangla({
  subsets: ["bengali", "latin"],
  variable: "--font-anek-bangla",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={`${anekBangla.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col w-11/12 mx-auto">
        <div>
          <Navbar></Navbar>
        </div>

        <div>{children}</div>

        <div>
          <Footer></Footer>
        </div>

      </body>
    </html>
  );
}
